#%RAML 1.0 DataType
uses:
  common-library: exchange_modules/af4cd7c0-6a28-476d-bb8d-cf50eed6b461/common-fragment/1.0.14/common-library-fragment.raml
type: object
properties:
  assessmnetReportResponse:
    type: object
    properties:
      userDetails:
        required: true
        type: common-library.userDetails
      assessmentdetails:
        required: true
        type: object
        properties:
          result:
            type: number
            required: true
            example: 90
      submitionDateTime:
        required: true
        type: common-library.submitionDateTime