#%RAML 1.0 Trait
headers:
  x-fms-transactionId:
    required: true
    type: string
    maxLength: 36
    minLength: 36
    example: hdsfhjdh-jxbv859-sjdf7643-374jhgfrgh
  x-fms-clientId:
    required: true
    type: string
    example: hsdfgysdhfcdshf37er6twgsdhfjcd
  x-fms-clientSecret:
    required: true
    type: string
    example: dsgfhaegur457r6ewsewegrfjesh