#%RAML 1.0 Library
traits:
  common-header: !include trait/common-header-trait.raml
  common-error-response: !include trait/common-error-response-trait.raml
types:
  get-assessment-response: !include dataType/get-assessment-response-dataType.raml
  post-assessment-request: !include dataType/post-assessment-request-dataType.raml
  post-assessment-response: !include dataType/post-assessment-response-dataType.raml
  userDetails: !include dataType/user-details-dataType.raml
  assessmentdetails: !include dataType/assessment-details-qa-dataType.raml
  submitionDateTime: !include dataType/submission-datetime-dataType.raml

    